"""store_doc_content_in_db_manual

Revision ID: 0003_store_doc_content
Revises: 0002_hoa_modules
Create Date: 2026-01-29 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0003_store_doc_content'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.LargeBinary(), nullable=True))
    op.alter_column('documents', 'storage_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'storage_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###
