"""add_session_id_to_analytics_events

Revision ID: 8469b921f350
Revises: 46c8bb361996
Create Date: 2026-03-11 14:46:27.475035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8469b921f350'
down_revision: Union[str, None] = '46c8bb361996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_events', sa.Column('session_id', sa.String(length=128), nullable=True))
    op.alter_column('analytics_events', 'path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('ix_analytics_user_id', table_name='analytics_events')
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.create_index('ix_analytics_user_id', 'analytics_events', ['user_id'], unique=False)
    op.alter_column('analytics_events', 'path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('analytics_events', 'session_id')
    # ### end Alembic commands ###
