"""auto fix missing columns

Revision ID: a3e45a5bb08d
Revises: 0012
Create Date: 2026-02-27 00:42:03.451908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3e45a5bb08d'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.drop_index('ix_announcements_tenant_published', table_name='announcements')
    op.create_index('ix_announcements_tenant_published', 'announcements', ['tenant_id', 'published_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_announcements_tenant_id'), 'announcements', ['tenant_id'], unique=False)
    op.drop_index('ix_arc_requests_tenant_unit', table_name='arc_requests')
    op.create_index(op.f('ix_arc_requests_tenant_id'), 'arc_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_arc_requests_unit_id'), 'arc_requests', ['unit_id'], unique=False)
    op.drop_index('ix_arc_reviews_tenant_req', table_name='arc_reviews')
    op.create_index(op.f('ix_arc_reviews_arc_request_id'), 'arc_reviews', ['arc_request_id'], unique=False)
    op.create_index(op.f('ix_arc_reviews_tenant_id'), 'arc_reviews', ['tenant_id'], unique=False)
    op.drop_index('ix_branding_settings_tenant', table_name='branding_settings')
    op.create_index(op.f('ix_branding_settings_tenant_id'), 'branding_settings', ['tenant_id'], unique=False)
    op.drop_index('ix_buildings_tenant', table_name='buildings')
    op.create_index(op.f('ix_buildings_tenant_id'), 'buildings', ['tenant_id'], unique=False)
    op.drop_index('ix_charges_tenant_unit_posted', table_name='charges')
    op.create_index(op.f('ix_charges_tenant_id'), 'charges', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_charges_unit_id'), 'charges', ['unit_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_document_id'), 'document_embeddings', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_tenant_id'), 'document_embeddings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.drop_index('ix_feature_flags_tenant', table_name='feature_flags')
    op.create_index(op.f('ix_feature_flags_tenant_id'), 'feature_flags', ['tenant_id'], unique=False)
    op.drop_index('ix_hearings_tenant_violation', table_name='hearings')
    op.create_index(op.f('ix_hearings_tenant_id'), 'hearings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_hearings_violation_id'), 'hearings', ['violation_id'], unique=False)
    op.drop_index('ix_invoices_tenant_unit_issued', table_name='invoices')
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_invoices_unit_id'), 'invoices', ['unit_id'], unique=False)
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.drop_index('ix_ledger_accounts_tenant_unit', table_name='ledger_accounts')
    op.create_index(op.f('ix_ledger_accounts_tenant_id'), 'ledger_accounts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ledger_accounts_unit_id'), 'ledger_accounts', ['unit_id'], unique=False)
    op.drop_index('ix_occupancies_tenant_unit', table_name='occupancies')
    op.drop_index('ix_occupancies_user', table_name='occupancies')
    op.create_index(op.f('ix_occupancies_tenant_id'), 'occupancies', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_occupancies_unit_id'), 'occupancies', ['unit_id'], unique=False)
    op.create_index(op.f('ix_occupancies_user_id'), 'occupancies', ['user_id'], unique=False)
    op.drop_index('ix_payments_tenant_unit_posted', table_name='payments')
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_payments_unit_id'), 'payments', ['unit_id'], unique=False)
    op.drop_index('ix_resident_profiles_tenant', table_name='resident_profiles')
    op.drop_index('ix_resident_profiles_user', table_name='resident_profiles')
    op.create_index(op.f('ix_resident_profiles_tenant_id'), 'resident_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_resident_profiles_user_id'), 'resident_profiles', ['user_id'], unique=False)
    op.add_column('tenant_users', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_index('ix_tenant_users_tenant_email', 'tenant_users', ['tenant_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_tenant_users_user_id'), 'tenant_users', ['user_id'], unique=False)
    op.add_column('tenants', sa.Column('community_type', sa.String(length=32), nullable=False))
    op.drop_index('ix_units_building', table_name='units')
    op.drop_index('ix_units_tenant', table_name='units')
    op.create_index(op.f('ix_units_tenant_id'), 'units', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_contacts_user_id'), 'user_contacts', ['user_id'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_index('ix_vendors_tenant', table_name='vendors')
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.drop_index('ix_violation_notices_tenant_violation', table_name='violation_notices')
    op.create_index(op.f('ix_violation_notices_tenant_id'), 'violation_notices', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_violation_notices_violation_id'), 'violation_notices', ['violation_id'], unique=False)
    op.drop_index('ix_violations_tenant_unit', table_name='violations')
    op.create_index(op.f('ix_violations_tenant_id'), 'violations', ['tenant_id'], unique=False)
    op.create_index('ix_violations_tenant_status', 'violations', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_violations_unit_id'), 'violations', ['unit_id'], unique=False)
    op.drop_index('ix_wo_events_tenant_wo', table_name='work_order_events')
    op.create_index(op.f('ix_work_order_events_tenant_id'), 'work_order_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_work_order_events_work_order_id'), 'work_order_events', ['work_order_id'], unique=False)
    op.drop_index('ix_work_orders_tenant_unit', table_name='work_orders')
    op.create_index('ix_work_orders_tenant_created', 'work_orders', ['tenant_id', 'created_by_user_id'], unique=False)
    op.create_index(op.f('ix_work_orders_tenant_id'), 'work_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_work_orders_unit_id'), 'work_orders', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_unit_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_tenant_id'), table_name='work_orders')
    op.drop_index('ix_work_orders_tenant_created', table_name='work_orders')
    op.create_index('ix_work_orders_tenant_unit', 'work_orders', ['tenant_id', 'unit_id'], unique=False)
    op.drop_index(op.f('ix_work_order_events_work_order_id'), table_name='work_order_events')
    op.drop_index(op.f('ix_work_order_events_tenant_id'), table_name='work_order_events')
    op.create_index('ix_wo_events_tenant_wo', 'work_order_events', ['tenant_id', 'work_order_id'], unique=False)
    op.drop_index(op.f('ix_violations_unit_id'), table_name='violations')
    op.drop_index('ix_violations_tenant_status', table_name='violations')
    op.drop_index(op.f('ix_violations_tenant_id'), table_name='violations')
    op.create_index('ix_violations_tenant_unit', 'violations', ['tenant_id', 'unit_id'], unique=False)
    op.drop_index(op.f('ix_violation_notices_violation_id'), table_name='violation_notices')
    op.drop_index(op.f('ix_violation_notices_tenant_id'), table_name='violation_notices')
    op.create_index('ix_violation_notices_tenant_violation', 'violation_notices', ['tenant_id', 'violation_id'], unique=False)
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.create_index('ix_vendors_tenant', 'vendors', ['tenant_id'], unique=False)
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_user_contacts_user_id'), table_name='user_contacts')
    op.drop_index(op.f('ix_units_tenant_id'), table_name='units')
    op.create_index('ix_units_tenant', 'units', ['tenant_id'], unique=False)
    op.create_index('ix_units_building', 'units', ['building_id'], unique=False)
    op.drop_column('tenants', 'community_type')
    op.drop_index(op.f('ix_tenant_users_user_id'), table_name='tenant_users')
    op.drop_index('ix_tenant_users_tenant_email', table_name='tenant_users')
    op.drop_column('tenant_users', 'status')
    op.drop_index(op.f('ix_resident_profiles_user_id'), table_name='resident_profiles')
    op.drop_index(op.f('ix_resident_profiles_tenant_id'), table_name='resident_profiles')
    op.create_index('ix_resident_profiles_user', 'resident_profiles', ['user_id'], unique=False)
    op.create_index('ix_resident_profiles_tenant', 'resident_profiles', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_payments_unit_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.create_index('ix_payments_tenant_unit_posted', 'payments', ['tenant_id', 'unit_id', 'posted_at'], unique=False)
    op.drop_index(op.f('ix_occupancies_user_id'), table_name='occupancies')
    op.drop_index(op.f('ix_occupancies_unit_id'), table_name='occupancies')
    op.drop_index(op.f('ix_occupancies_tenant_id'), table_name='occupancies')
    op.create_index('ix_occupancies_user', 'occupancies', ['user_id'], unique=False)
    op.create_index('ix_occupancies_tenant_unit', 'occupancies', ['tenant_id', 'unit_id'], unique=False)
    op.drop_index(op.f('ix_ledger_accounts_unit_id'), table_name='ledger_accounts')
    op.drop_index(op.f('ix_ledger_accounts_tenant_id'), table_name='ledger_accounts')
    op.create_index('ix_ledger_accounts_tenant_unit', 'ledger_accounts', ['tenant_id', 'unit_id'], unique=False)
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_index(op.f('ix_invoices_unit_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.create_index('ix_invoices_tenant_unit_issued', 'invoices', ['tenant_id', 'unit_id', 'issued_at'], unique=False)
    op.drop_index(op.f('ix_hearings_violation_id'), table_name='hearings')
    op.drop_index(op.f('ix_hearings_tenant_id'), table_name='hearings')
    op.create_index('ix_hearings_tenant_violation', 'hearings', ['tenant_id', 'violation_id'], unique=False)
    op.drop_index(op.f('ix_feature_flags_tenant_id'), table_name='feature_flags')
    op.create_index('ix_feature_flags_tenant', 'feature_flags', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_document_embeddings_tenant_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_document_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_charges_unit_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_tenant_id'), table_name='charges')
    op.create_index('ix_charges_tenant_unit_posted', 'charges', ['tenant_id', 'unit_id', 'posted_at'], unique=False)
    op.drop_index(op.f('ix_buildings_tenant_id'), table_name='buildings')
    op.create_index('ix_buildings_tenant', 'buildings', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_branding_settings_tenant_id'), table_name='branding_settings')
    op.create_index('ix_branding_settings_tenant', 'branding_settings', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_arc_reviews_tenant_id'), table_name='arc_reviews')
    op.drop_index(op.f('ix_arc_reviews_arc_request_id'), table_name='arc_reviews')
    op.create_index('ix_arc_reviews_tenant_req', 'arc_reviews', ['tenant_id', 'arc_request_id'], unique=False)
    op.drop_index(op.f('ix_arc_requests_unit_id'), table_name='arc_requests')
    op.drop_index(op.f('ix_arc_requests_tenant_id'), table_name='arc_requests')
    op.create_index('ix_arc_requests_tenant_unit', 'arc_requests', ['tenant_id', 'unit_id'], unique=False)
    op.drop_index(op.f('ix_announcements_tenant_id'), table_name='announcements')
    op.drop_index('ix_announcements_tenant_published', table_name='announcements')
    op.create_index('ix_announcements_tenant_published', 'announcements', ['tenant_id', 'published_at'], unique=False)
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
