"""add_user_preferences_final

Revision ID: d13fbe236518
Revises: 8469b921f350
Create Date: 2026-03-14 15:10:19.521721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13fbe236518'
down_revision: Union[str, None] = '8469b921f350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['tenant_id', 'user_id', 'is_read'], unique=False)
    op.add_column('tenant_users', sa.Column('notification_email', sa.Boolean(), nullable=False))
    op.add_column('tenant_users', sa.Column('notification_sms', sa.Boolean(), nullable=False))
    op.add_column('tenant_users', sa.Column('notification_push', sa.Boolean(), nullable=False))
    op.add_column('tenant_users', sa.Column('pref_community_news', sa.Boolean(), nullable=False))
    op.add_column('tenant_users', sa.Column('pref_board_reports', sa.Boolean(), nullable=False))
    op.add_column('tenant_users', sa.Column('pref_social_events', sa.Boolean(), nullable=False))
    op.add_column('tenant_users', sa.Column('language', sa.String(length=10), nullable=False))
    op.add_column('tenant_users', sa.Column('timezone', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_users', 'timezone')
    op.drop_column('tenant_users', 'language')
    op.drop_column('tenant_users', 'pref_social_events')
    op.drop_column('tenant_users', 'pref_board_reports')
    op.drop_column('tenant_users', 'pref_community_news')
    op.drop_column('tenant_users', 'notification_push')
    op.drop_column('tenant_users', 'notification_sms')
    op.drop_column('tenant_users', 'notification_email')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
