"""add missing columns to tenant_users and other models

Revision ID: d3b8422e1aeb
Revises: a3e45a5bb08d
Create Date: 2026-03-10 14:59:28.688793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b8422e1aeb'
down_revision: Union[str, None] = 'a3e45a5bb08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tenant_users_account_number'), 'tenant_users', ['account_number'], unique=True)
    op.create_index(op.f('ix_tenant_users_invitation_token'), 'tenant_users', ['invitation_token'], unique=True)
    op.create_index(op.f('ix_tenant_users_registration_number'), 'tenant_users', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_users_registration_number'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_invitation_token'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_account_number'), table_name='tenant_users')
    # ### end Alembic commands ###
